### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by w-lfchen**
https://discord.com/channels/968818197824417822/1052139415637610516/1052139683162886234

### CODE REVIEW

**Comment by Danghor** [comment]
Fixed by [b288f2c](https://github.com/FOP-2223/FOP-2223-H08-Student/commit/b288f2c41b095d5c04d614b8d9669ac7b5c0383a)

**Comment by fm-sys** [comment]
Out of interest:

What are the differences between both solutions, and why was it decided to go with the first one?

```java
private <T extends Throwable> void testException(ArrayCalculator sut, double[][] array, double max, Class<T> expectedException, String expectedExceptionMessage) {...}

private void testException(ArrayCalculator sut, double[][] array, double max, Class<? extends Throwable> expectedException, String expectedExceptionMessage) {...}
```
As the second one seems much easier to read for students who are new to generics...

**Comment by Danghor** [comment]
Tbh, the first one is much closer to the C#-syntax and I am used to that one. Since I don't want to break any functionality for the students who are in the middle of solving the exercise, I went with the syntax I understand better to avoid making mistakes. Maybe the second works just as well, but I would have to do more research, since the ?-notation is unfamiliar to me.

**Comment by fm-sys** [comment]
Just for info, the "?" is a so called "wildcard" . You can read more about it here:

https://docs.oracle.com/javase/tutorial/extra/generics/wildcards.html

**Pull request closed without merging**
